### ISSUE TITLE
Initiate the module

### ISSUE THREAD

**Issue by claustres** [kalisio/kMap#3]
* [x] create a 2D map view
* [x] create a 3D globe view
* [x] service-layers mixin to bind each view to a real-time location/orientation tracking service
* [x] location field binded to a geocoding service with auto complete
* [x] geolocation mixin

**Comment by cnouguier** [comment]
First version of service-layers is done. Furthermore, it is necessary to enhance the way the layer is refreshed when the data are updated. Indeed, we are using the 'always' strategy to stream the data from the service using Reactive. In response to the subscription, we clear the layer and add to the layer the response data. 
Creating #6
